name: Verificare Stoc Zilnica

on:
  schedule:
    - cron: '0 9,18 * * *' # Ruleaza la ora 09:00 si 18:00 (ora UTC)
  workflow_dispatch:      # Permite sa-l pornesti si manual cand vrei tu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout cod
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalare librarii
        run: pip install -r requirements.txt

      - name: Ruleaza scriptul
        run: python tracker.py

      - name: Salveaza datele in GitHub
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add istoric_stoc.csv
          git commit -m "Update stoc: $(date)" || echo "Nicio modificare"
          git push
